// src/app/layout.tsx
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ClientLayout from './components/ClientLayout';
import './globals.css';
import { AppProvider } from '@/context/AppContext';
import { CartProvider } from '@/context/CartContext'; // Import CartProvider
import { ThemeProvider } from '@/context/ThemeContext'; // Import ThemeProvider
import { UserProvider } from '@/context/UserContext'; // Import UserProvider

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap with all providers */}
        <ThemeProvider>
          <UserProvider>
            <CartProvider>
              <AppProvider> {/* AppProvider should be the innermost if it consumes other contexts */}
                <ClientLayout>{children}</ClientLayout>
              </AppProvider>
            </CartProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}